### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by sskras** [DavidEGrayson/midipix-packages#1]
(not an actual issue)

I saw this intriguing piece of text just now:
```
- passix - passport.mid and Posix (.com not available)
- passyx - passport.mid and Posix
- pannix - Posix and Nix (.com not available)
- pawnix - Posix and Windows and Nix
```

`pawnix` sounds very cute!

I had similar idea of combining things into a *nix-like environment that would be similar to Cygwin (but faster), also similar to MSYS2 (with regard to package management) and that would have better integration (even including X11 rendering), like project Swan [dead at the moment].

Midipix seemed like a perfect match for it, and I also started collecting ideas about the easy readable names that would reflect its' nature.  Here are some:
```
- wxi    – Windows-to-X/open Interface
- wxsi   – Windows-to-X/open System Interface
- ntix   – NT Interface of X/Open
- pointx – Portable OS Interface NT-to-X/open [too many collisions in global search engines]
- xpoint – X/open Portable OS Interface for NT [also too many collisions]
- pint   – Portable Interface for NT [the same colliding issue]
```

Out ot these I like `ntix` the most (because it's short and sounds like some kind of *nix: `entix`).

Of course, as most of these handles would be already occupied on Twitter and GitHub, I had an idea of prepending the name with `lib` prefix for that use:

`libntix`

Just a two cents.

**Comment by DavidEGrayson** [comment]
Hey.  I was never really a part of the midipix project and I haven't done anything with it for many years.  I think they have a mailing list and an IRC channel you could chat on if you want to start discussions like this.

**Comment by sskras** [comment]
That's OK, I agree and I already have landed on their IRC channel.

Here I just wanted to thank you for the list of nice names for potential project + I added the few ideas in case someone (like me) would do research in similar direction.

Closing the "issue", and thanks again. :)
